### ISSUE TITLE
Black Triangle #1: Implement embedded players for different media sites

### ISSUE THREAD

**Issue by jonvuri** [jonvuri/tonlist#1]
Try out third-party React components, or home-grown embeds (like oembed or iframes) if unavailable, to embed and auto-play media from the following platforms given a link to content on them:

- [x] Youtube
- [x] Soundcloud
- [x] Instagram
- [x] X

For each platform, note the solution that worked, any challenges encountered, and whether they support all of the following features:
- [x] Auto-play on load with no user interaction and without the user signing in to that platform (assuming the user has already interacted with the page in general via a click or something, to enable music/video play in general)
- [x] Seeking to a specific point in the media before / during starting auto-play
- [x] Arbitrary sizing

**Comment by devonfox** [comment]
Instagram and X are currently not included.  I also have not yet looked into Arbitrary sizing, although this is possible with ReactPlayer props.
